services:
  govd-bot:
    image: govd-bot
    container_name: govd-bot
    restart: unless-stopped
    networks:
      - govd-network
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./cookies:/app/cookies
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: govd
      MARIADB_USER: govd
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: example
    networks:
      - govd-network

networks:
  govd-network:
    driver: bridge

